name: Build APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with Buildozer
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          command: buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app-apk
          path: bin/*.apk
